### PR TITLE
add pgSQL 

### PR DESCRIPTION
**Pull request by dfrozen**
Please check this changes? have same trouble 
1. in admin interface  everytime ask to save config
2. In restore dont work search backup files.

### CODE REVIEW

**Comment by simatec** [comment]
Changing config names is not a good thing.
There are users who use mysql backups and they would switch off the mysql backup after an update. Please fix it before I can take over the PR

**Comment by dfrozen** [comment]
ok i got you

**Comment by dfrozen** [comment]
1. switch off the mysql backup after an update.(fix)
2. admin interface everytime ask to save config (fix)
3. restore don`t work search backup files. (fix)

**Comment by simatec** [comment]
does the current version of the backup work properly?  Then I could take it over for testing.

**Comment by dfrozen** [comment]
> does the current version of the backup work properly? Then I could take it over for testing.
A backup copy is created without problems.
  After merging with 1.5.6
1. in admin interface everytime ask to save config
2. In restore dont work search backup files.
Check what I did wrong again.

**Comment by simatec** [comment]
sqlConfig is not good for Config at Update. Many User have a mysql Backup running ... after Update dont run this. Never change the Config Name.  

The Bug with save in admin is not good. Please fix this ...

**Comment by simatec** [comment]
some of your changes are too extreme and are not necessary.  we only add unnecessary bugs.  I will take a look at the backup version during the days.  But just the changes in the index_m and changes in the config names are not good

**Comment by dfrozen** [comment]
I do not insist on applying my changes if they are too extreme. I am a bad programmer, so that it would be necessary a lot of what is in history is my experiments, and a lot was unnecessary and canceled. You may not accept my PR. I can always use it solely for personal use. I like to use your adapter, but it did not know how to work with myets database. I could not make good and correct code right away.

**Comment by simatec** [comment]
This is not a problem.  I would be happy to incorporate this in one of the next versions.  What information is needed?  The same as with mysql (host, port, username and password)?  or more is needed.  I would possibly build the whole thing a little differently and not at all with a lot of extra code.

**Comment by dfrozen** [comment]
for standart use Host, pgSqlPort, DataBaseName, UserName, Password. Scripts (backup/restore) - 100% work.But in the rest of the code, I got confused. although by version 1.5.4 everything spoke of victory.

**Comment by simatec** [comment]
No Problem ... I will write this on Todo in the next versions.  currently I just have to get the error handling for sentry.io under control

**Comment by dfrozen** [comment]
thanks for understanding

**Comment by simatec** [comment]
Sorry that it took a little longer. I programmed pgsql in 1.8.0-beta.1. Since I don't use this myself, I would be happy if you could test the backup and restore.

Thank you

**Pull request closed without merging**
