### PR TITLE
Add support for sending notifications via discord

### PR DESCRIPTION
**Pull request by crycode-de**
This PR adds support for sending notifications via discord.
Requires [ioBroker.discord](https://github.com/crycode-de/ioBroker.discord) >=2.1 (currently in the latest repo).

In the adapter config you can select Discord as `notificationsType` and the target to send the notification to.
Possible targets are loaded from the selected (and running) ioBroker.discord instance.
Targets may be a single user (direct message) or a server channel.

grafik

grafik

### CODE REVIEW

**Comment by simatec** [comment]
@crycode-de 
Could it be that you have forgotten the sendTo message function in the main.js for "discordTarget" in your PR?

Since I haven't set up Discord, I unfortunately can't test this.
I just noticed that you have a sendTo in the index_m.js to fill the select, but it is never processed.

Can you please check this?

**Comment by crycode-de** [comment]
@simatec Should be fine.
The `sendTo` sends the request directly to the selected discord instance.
See https://github.com/simatec/ioBroker.backitup/pull/970/files#diff-14c139e634e73d8b6c0aac4b6b78b46010a5d26250480f955e57bc91261d0904R1226

It's working as expected.
grafik

**Comment by simatec** [comment]
From which state or object does it get the values exactly? Can you give me a path here?

So or "discord.0.target"

**Comment by crycode-de** [comment]
The request is send to the discord instance like
```js
sendTo('discord.0', 'getNotificationTargets', {}, function(targetList) { ... });
```

The discord instance responds with an array (`targetList`) like:
```js
[
  { value: '', label: '---' }, // always present - no target
  {
    label: 'crycode', // name of a discord user seen by the discord instance
    value: '490222742801481728' // userID of that user in discord
  },
  {
    label: 'Zuhause » Text Channels » allgemein', // discord server name » channel group name » channel name
    value: '980038440525635644/980038441372901418' // serverID/channelID
  }
```
This values are determined internally by the discord adapter instance based on the users, servers and server channels seen by the discord bot.

**Pull request merged**
