### PR TITLE
(bluefox) refactoring

### PR DESCRIPTION
**Pull request by GermanBluefox**
Not tested. Please use as base for translations.

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Wait a minute with merge. Will prepare

**Comment by GermanBluefox** [comment]
Ready to merge

**Comment by GermanBluefox** [comment]
Don't forget: ioBroker is international project and if you use the names and comments in german you limit the usage and possible maintenance to german users. Russian users are active too and they cannot understand german :)

**Comment by simatec** [comment]
I have a error!!

backitup.0 | 2018-07-17 18:15:10.089 | error | TypeError: Cannot read property 'host' of undefined

**Pull request merged**
